name: datapulse
version: '0.1.0'

profile: datapulse

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

clean-targets:
  - target
  - dbt_packages

seeds:
  datapulse:
    seed_division_origin:
      +schema: marts
      +column_types:
        division: varchar(50)
        origin: varchar(20)

models:
  datapulse:
    bronze:
      +materialized: table
      +schema: bronze
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      dims:
        +materialized: table
      facts:
        +materialized: table
      aggs:
        +materialized: table
      features:
        +materialized: table
