"""Rollback utilities for pipeline stages.

Provides per-stage rollback functions that undo partial data changes
when a pipeline stage fails.
"""

from __future__ import annotations

from uuid import UUID

from sqlalchemy import text
from sqlalchemy.orm import Session

from datapulse.logging import get_logger

log = get_logger(__name__)


def rollback_bronze(session: Session, run_id: UUID) -> int:
    """Delete all bronze rows inserted by a specific pipeline run.

    Requires: bronze.sales._pipeline_run_id column.
    Returns: number of rows deleted.
    """
    log.info("rollback_bronze_start", run_id=str(run_id))
    try:
        result = session.execute(
            text("DELETE FROM bronze.sales WHERE _pipeline_run_id = :run_id"),
            {"run_id": str(run_id)},
        )
        deleted = result.rowcount  # type: ignore[attr-defined]
        session.commit()
        log.info("rollback_bronze_done", run_id=str(run_id), rows_deleted=deleted)
        return deleted
    except Exception as exc:
        session.rollback()
        log.error("rollback_bronze_failed", run_id=str(run_id), error=str(exc))
        return 0


def rollback_forecasting(session: Session, run_id: UUID) -> int:
    """Delete forecast rows generated by a specific pipeline run.

    Returns: number of rows deleted.
    """
    log.info("rollback_forecasting_start", run_id=str(run_id))
    try:
        result = session.execute(
            text("DELETE FROM public_marts.forecasts WHERE pipeline_run_id = :run_id"),
            {"run_id": str(run_id)},
        )
        deleted = result.rowcount  # type: ignore[attr-defined]
        session.commit()
        log.info("rollback_forecasting_done", run_id=str(run_id), rows_deleted=deleted)
        return deleted
    except Exception as exc:
        session.rollback()
        log.error("rollback_forecasting_failed", run_id=str(run_id), error=str(exc))
        return 0


def rollback_stage(session: Session, stage: str, run_id: UUID) -> int:
    """Dispatch rollback for a specific stage.

    Not all stages support rollback (dbt staging/marts are idempotent).
    Returns rows affected, or 0 if stage has no rollback logic.
    """
    rollback_map = {
        "bronze": rollback_bronze,
        "forecasting": rollback_forecasting,
    }
    handler = rollback_map.get(stage)
    if handler is None:
        log.info("rollback_skipped", stage=stage, reason="idempotent_stage")
        return 0
    return handler(session, run_id)
