// Typed POS transaction endpoints. Wraps ApiClient with OpenAPI-generated
// request/response types regenerated by Sub-PR 5 (`make openapi` then
// `npm run codegen` in pos-desktop).

import type { ApiClient } from "@pos/api/client";
import type { paths } from "@pos/api/types";

type CreateResp =
  paths["/api/v1/pos/transactions"]["post"]["responses"]["201"]["content"]["application/json"];

type AddItemBody =
  paths["/api/v1/pos/transactions/{transaction_id}/items"]["post"]["requestBody"] extends
    { content: { "application/json": infer B } }
    ? B
    : never;
type AddItemResp =
  paths["/api/v1/pos/transactions/{transaction_id}/items"]["post"]["responses"]["201"]["content"]["application/json"];

type CommitBody =
  paths["/api/v1/pos/transactions/commit"]["post"]["requestBody"] extends
    { content: { "application/json": infer B } }
    ? B
    : never;
type CommitResp =
  paths["/api/v1/pos/transactions/commit"]["post"]["responses"]["200"]["content"]["application/json"];

type VoidBody =
  paths["/api/v1/pos/transactions/{transaction_id}/void"]["post"]["requestBody"] extends
    { content: { "application/json": infer B } }
    ? B
    : never;
type VoidResp =
  paths["/api/v1/pos/transactions/{transaction_id}/void"]["post"]["responses"]["200"]["content"]["application/json"];

export interface TransactionEndpoints {
  create: () => Promise<CreateResp>;
  addItem: (txnId: number, body: AddItemBody) => Promise<AddItemResp>;
  commit: (body: CommitBody) => Promise<CommitResp>;
  voidTxn: (txnId: number, body: VoidBody) => Promise<VoidResp>;
}

export function createTransactionEndpoints(client: ApiClient): TransactionEndpoints {
  return {
    create: () => client.request("POST", "/api/v1/pos/transactions", {}),
    addItem: (txnId, body) =>
      client.request("POST", `/api/v1/pos/transactions/${txnId}/items`, body),
    commit: (body) => client.request("POST", "/api/v1/pos/transactions/commit", body),
    voidTxn: (txnId, body) =>
      client.request("POST", `/api/v1/pos/transactions/${txnId}/void`, body),
  };
}
