-- Migration: 088 — Add 'voucher' to pos.transactions.payment_method CHECK
-- Layer: POS operational
-- Idempotent.

-- Drop the inline CHECK constraint (name auto-generated by Postgres).
-- We look it up by column rather than guessing the name.
DO $$
DECLARE
    con_name TEXT;
BEGIN
    SELECT conname INTO con_name
    FROM pg_constraint
    WHERE conrelid = 'pos.transactions'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) LIKE '%payment_method%IN%';
    IF con_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE pos.transactions DROP CONSTRAINT %I', con_name);
    END IF;
END $$;

-- Re-add with 'voucher' included. Named for future idempotency.
ALTER TABLE pos.transactions
    ADD CONSTRAINT pos_transactions_payment_method_check
    CHECK (payment_method IN ('cash', 'card', 'insurance', 'voucher', 'mixed'));

COMMENT ON CONSTRAINT pos_transactions_payment_method_check ON pos.transactions IS
    'Allowed payment methods at checkout. Must match datapulse.pos.constants.PaymentMethod enum.';
