/// Container table for all DAX measures. No data rows.
table _Measures
	isHidden
	lineageTag: a21ef15a-6e27-4b94-9253-fd9b382ac0f1

	/// Net of discounts, includes returns
	measure 'Net Revenue' = SUM(fct_sales[net_amount])
		formatString: #,##0.00
		displayFolder: Core KPIs
		lineageTag: 7a76cee6-66ec-4e2b-a461-99475b4654c3

	/// Net revenue excluding return transactions
	measure 'Net Revenue (Excl Returns)' =
			CALCULATE(
			    SUM(fct_sales[net_amount]),
			    fct_sales[is_return] = FALSE
			)
		formatString: #,##0.00
		displayFolder: Core KPIs
		lineageTag: ccbdd226-e90f-42ca-b982-c15c9c669069

	/// Before discounts
	measure 'Gross Revenue' = SUM(fct_sales[sales])
		formatString: #,##0.00
		displayFolder: Core KPIs
		lineageTag: 033d5c19-cf63-4863-abc5-e31c78fe79d0

	/// Units sold (negative for returns)
	measure 'Total Quantity' = SUM(fct_sales[quantity])
		formatString: #,##0.00
		displayFolder: Core KPIs
		lineageTag: 3f3441aa-a9d4-40c2-91c1-df1df824a34b

	/// Distinct invoice count
	measure 'Unique Invoices' = DISTINCTCOUNT(fct_sales[invoice_id])
		formatString: #,##0
		displayFolder: Core KPIs
		lineageTag: 09a27b3a-d160-478c-b669-9ef4e4020d25

	/// Revenue per invoice
	measure 'Avg Invoice Value' =
			DIVIDE(
			    [Net Revenue],
			    [Unique Invoices],
			    0
			)
		formatString: #,##0.00
		displayFolder: Core KPIs
		lineageTag: 3c18e55f-5726-48de-a669-785c81f75e57

	/// Distinct customers in context
	measure 'Unique Customers' = CALCULATE(DISTINCTCOUNT(fct_sales[customer_key]), fct_sales[customer_key] <> -1)
		formatString: #,##0
		displayFolder: Core KPIs
		lineageTag: 6ba65fb5-7ad3-472e-af7f-b5072a8bd791

	/// Distinct products sold in context
	measure 'Unique Products Sold' = DISTINCTCOUNT(fct_sales[product_key])
		formatString: #,##0
		displayFolder: Core KPIs
		lineageTag: 608c657a-5ad0-4098-a9ea-cd828a9facb5

	/// Total discount amount
	measure 'Total Discount' = SUM(fct_sales[discount])
		formatString: #,##0.00
		displayFolder: Discount Analysis
		lineageTag: a6732a7f-5e7e-4703-a943-9d121077bd82

	/// Discount as percentage of gross
	measure 'Discount Rate %' =
			VAR _gross = SUM(fct_sales[sales])
			VAR _disc = SUM(fct_sales[discount])
			RETURN
			    DIVIDE(_disc, _gross, 0)
		formatString: 0.00%
		displayFolder: Discount Analysis
		lineageTag: 1d165460-8384-44b6-aa43-2dd38b077749

	/// Net amount as percentage of gross
	measure 'Net to Gross Ratio' =
			VAR _net = SUM(fct_sales[net_amount])
			VAR _gross = SUM(fct_sales[sales])
			RETURN
			    DIVIDE(_net, _gross, 0)
		formatString: 0.00%
		displayFolder: Discount Analysis
		lineageTag: 86044767-6cd6-4ad8-ba36-940c63f9152d

	/// Average discount per invoice
	measure 'Avg Discount per Invoice' =
			DIVIDE(
			    [Total Discount],
			    [Unique Invoices],
			    0
			)
		formatString: #,##0.00
		displayFolder: Discount Analysis
		lineageTag: 8d27805f-d7b8-40e2-960c-1751a2214548

	/// Revenue from Cash billing
	measure 'Cash Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_billing[billing_group] = "Cash"
			)
		formatString: #,##0.00
		displayFolder: Revenue Mix
		lineageTag: f1fac514-7968-46bb-9076-7e429e2c9dd3

	/// Revenue from Credit billing
	measure 'Credit Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_billing[billing_group] = "Credit"
			)
		formatString: #,##0.00
		displayFolder: Revenue Mix
		lineageTag: 94a45a3f-af34-4e16-a255-cca9dad92e92

	/// Revenue from Delivery billing
	measure 'Delivery Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_billing[billing_group] = "Delivery"
			)
		formatString: #,##0.00
		displayFolder: Revenue Mix
		lineageTag: e6091fe2-8277-4da4-a0ec-0fccd4f4a85c

	/// Revenue from Delivery Credit billing
	measure 'Delivery Credit Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_billing[billing_group] = "Delivery Credit"
			)
		formatString: #,##0.00
		displayFolder: Revenue Mix
		lineageTag: d7b5744d-fac5-45b2-b720-0222759bbaed

	/// Revenue from Pick-Up billing
	measure 'Pickup Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_billing[billing_group] = "Pick-Up"
			)
		formatString: #,##0.00
		displayFolder: Revenue Mix
		lineageTag: 9182ed33-aec8-4ab9-b3ca-0858e551b68e

	/// Revenue from insured transactions
	measure 'Insurance Revenue' =
			CALCULATE(
			    [Net Revenue],
			    fct_sales[has_insurance] = TRUE
			)
		formatString: #,##0.00
		displayFolder: Revenue Mix
		lineageTag: dc91a356-421c-4e66-8eb0-980a5d1f31f3

	/// Cash share of total revenue
	measure 'Cash %' =
			VAR _val = [Cash Revenue]
			VAR _all = CALCULATE([Net Revenue], REMOVEFILTERS(dim_billing))
			RETURN
			    DIVIDE(_val, _all, 0)
		formatString: 0.00%
		displayFolder: Revenue Mix
		lineageTag: cda47f96-ac61-4c7c-862a-eb2586e71345

	/// Credit share of total revenue
	measure 'Credit %' =
			VAR _val = [Credit Revenue]
			VAR _all = CALCULATE([Net Revenue], REMOVEFILTERS(dim_billing))
			RETURN
			    DIVIDE(_val, _all, 0)
		formatString: 0.00%
		displayFolder: Revenue Mix
		lineageTag: a656b811-ddd9-4af1-8319-fcabe4468a48

	/// Delivery share of total revenue
	measure 'Delivery %' =
			VAR _val = [Delivery Revenue]
			VAR _all = CALCULATE([Net Revenue], REMOVEFILTERS(dim_billing))
			RETURN
			    DIVIDE(_val, _all, 0)
		formatString: 0.00%
		displayFolder: Revenue Mix
		lineageTag: 717a8f6a-53b6-485c-aefe-57e56ec82de9

	/// Delivery Credit share of total revenue
	measure 'Delivery Credit %' =
			VAR _val = [Delivery Credit Revenue]
			VAR _all = CALCULATE([Net Revenue], REMOVEFILTERS(dim_billing))
			RETURN
			    DIVIDE(_val, _all, 0)
		formatString: 0.00%
		displayFolder: Revenue Mix
		lineageTag: 8a6daa6a-1f39-4df7-a688-d746f91a6bd4

	/// Pick-Up share of total revenue
	measure 'Pickup %' =
			VAR _val = [Pickup Revenue]
			VAR _all = CALCULATE([Net Revenue], REMOVEFILTERS(dim_billing))
			RETURN
			    DIVIDE(_val, _all, 0)
		formatString: 0.00%
		displayFolder: Revenue Mix
		lineageTag: 67c3a3af-5f98-40af-b162-ba82406a89a0

	/// Insurance share of total revenue
	measure 'Insurance %' =
			VAR _ins = [Insurance Revenue]
			VAR _all = CALCULATE([Net Revenue], REMOVEFILTERS(fct_sales[has_insurance]))
			RETURN
			    DIVIDE(_ins, _all, 0)
		formatString: 0.00%
		displayFolder: Revenue Mix
		lineageTag: e0013eef-ab24-415e-a8e3-1d4556c5186f

	/// Signed return value (negative) for accounting
	measure 'Return Net Effect' =
			CALCULATE(
			    SUM(fct_sales[net_amount]),
			    fct_sales[is_return] = TRUE
			)
		formatString: #,##0.00
		displayFolder: Returns
		lineageTag: bd068be6-4bc2-4f82-8dd3-e637f9c90b17

	/// Absolute return value for operational reporting
	measure 'Return Value' = ABS([Return Net Effect])
		formatString: #,##0.00
		displayFolder: Returns
		lineageTag: 85d3cc7a-88ee-467f-a5f6-edf01b75a07e

	/// Signed units returned (negative)
	measure 'Return Quantity (Signed)' =
			CALCULATE(
			    SUM(fct_sales[quantity]),
			    fct_sales[is_return] = TRUE
			)
		formatString: #,##0.00
		displayFolder: Returns
		lineageTag: 4578c82d-be21-4c2a-9e40-058d0f3b7e0a

	/// Absolute units returned
	measure 'Return Quantity' = ABS([Return Quantity (Signed)])
		formatString: #,##0.00
		displayFolder: Returns
		lineageTag: c31cd5f9-9d96-4cd8-83cc-5fcd03037f6c

	/// Return magnitude vs forward sales
	measure 'Return Rate %' =
			DIVIDE(
			    [Return Value],
			    [Net Revenue (Excl Returns)],
			    0
			)
		formatString: 0.00%
		displayFolder: Returns
		lineageTag: b209e92b-dabb-4e6f-aecb-e3004b45ff60

	/// Count of return transactions
	measure 'Return Invoices' =
			CALCULATE(
			    DISTINCTCOUNT(fct_sales[invoice_id]),
			    fct_sales[is_return] = TRUE
			)
		formatString: #,##0
		displayFolder: Returns
		lineageTag: 86495f89-1026-4870-a9f6-b3d77c5f423b

	/// Return units vs sold units
	measure 'Return Qty Rate %' =
			VAR _retQty = [Return Quantity]
			VAR _fwdQty = CALCULATE(SUM(fct_sales[quantity]), fct_sales[is_return] = FALSE)
			RETURN
			    DIVIDE(_retQty, _fwdQty, 0)
		formatString: 0.00%
		displayFolder: Returns
		lineageTag: 591cb41b-1656-4fcc-b649-1337829a9a7b

	/// Revenue from walk-in customers
	measure 'Walk-in Revenue' =
			CALCULATE(
			    [Net Revenue],
			    fct_sales[is_walk_in] = TRUE
			)
		formatString: #,##0.00
		displayFolder: Customer Analytics
		lineageTag: 7583c56c-5fe9-4213-b544-a3e7bb4e8fdb

	/// Revenue from account customers
	measure 'Account Revenue' =
			CALCULATE(
			    [Net Revenue],
			    fct_sales[is_walk_in] = FALSE
			)
		formatString: #,##0.00
		displayFolder: Customer Analytics
		lineageTag: 77256485-4047-4265-87e6-efe5ebd7f2dd

	/// Walk-in share of total revenue
	measure 'Walk-in %' =
			VAR _walkin = [Walk-in Revenue]
			VAR _all = CALCULATE([Net Revenue], REMOVEFILTERS(fct_sales[is_walk_in]))
			RETURN
			    DIVIDE(_walkin, _all, 0)
		formatString: 0.00%
		displayFolder: Customer Analytics
		lineageTag: 6ba70335-d457-432e-a98d-215c44ea2dc8

	/// Distinct customers with insurance
	measure 'Insurance Customers' =
			CALCULATE(
			    DISTINCTCOUNT(fct_sales[customer_key]),
			    fct_sales[has_insurance] = TRUE
			)
		formatString: #,##0
		displayFolder: Customer Analytics
		lineageTag: c2be77ab-24ed-4a9b-9b6f-b0d69ba5463a

	/// Average revenue per customer
	measure 'Revenue per Customer' =
			DIVIDE(
			    [Net Revenue],
			    [Unique Customers],
			    0
			)
		formatString: #,##0.00
		displayFolder: Customer Analytics
		lineageTag: f6251b9a-0221-4ed5-9dfe-d4fc2ba17d21

	/// Average basket depth per customer
	measure 'Avg Items per Customer' =
			DIVIDE(
			    [Total Quantity],
			    [Unique Customers],
			    0
			)
		formatString: #,##0.00
		displayFolder: Customer Analytics
		lineageTag: ff4749c1-1928-480d-b98a-5a6f593ba892

	/// Revenue from Active status products
	measure 'Active Product Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_product[drug_status] = "Active"
			)
		formatString: #,##0.00
		displayFolder: Product Analytics
		lineageTag: 4a8deceb-c369-465f-9a27-1f2f77a22c21

	/// Active products share of revenue
	measure 'Active Product %' =
			VAR _active = [Active Product Revenue]
			VAR _all = CALCULATE([Net Revenue], REMOVEFILTERS(dim_product[drug_status]))
			RETURN
			    DIVIDE(_active, _all, 0)
		formatString: 0.00%
		displayFolder: Product Analytics
		lineageTag: a3abb5f7-8532-49b7-9916-f11a3912171f

	/// Revenue from New status products
	measure 'New Product Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_product[drug_status] = "New"
			)
		formatString: #,##0.00
		displayFolder: Product Analytics
		lineageTag: 74de1ce1-8f62-4d1a-bb74-80f9f04f5722

	/// Revenue from Delisted/Cancelled products
	measure 'Discontinued Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_product[drug_status] IN {"Delisted", "Cancelled"}
			)
		formatString: #,##0.00
		displayFolder: Product Analytics
		lineageTag: 854fc2ff-81ce-4500-acd8-b9ecc6e2b2f4

	/// Revenue from temporary (-T) products
	measure 'Temporary Product Revenue' =
			CALCULATE(
			    [Net Revenue],
			    dim_product[is_temporary] = TRUE
			)
		formatString: #,##0.00
		displayFolder: Product Analytics
		lineageTag: b7387285-790f-4e5a-8f2b-990d758bbac0

	/// Distinct products in context
	measure 'Product Count' = DISTINCTCOUNT(dim_product[product_key])
		formatString: #,##0
		displayFolder: Product Analytics
		lineageTag: fc2eec32-4569-47df-aa0c-5393e4ca11b6

	/// Average revenue per product sold
	measure 'Revenue per Product' =
			DIVIDE(
			    [Net Revenue],
			    DISTINCTCOUNT(fct_sales[product_key]),
			    0
			)
		formatString: #,##0.00
		displayFolder: Product Analytics
		lineageTag: 578a21d5-86b4-4a59-8f30-2635b6991d86

	/// Pareto: top 20% products share of revenue
	measure 'Top 20% Product Revenue %' =
			VAR _totalRev = CALCULATE([Net Revenue], REMOVEFILTERS(dim_product))
			VAR _productTable =
			    ADDCOLUMNS(
			        SUMMARIZE(fct_sales, dim_product[product_key]),
			        "@Rev", [Net Revenue]
			    )
			VAR _sorted = TOPN(
			    ROUNDUP(COUNTROWS(_productTable) * 0.2, 0),
			    _productTable,
			    [@Rev], DESC
			)
			VAR _topRev = SUMX(_sorted, [@Rev])
			RETURN
			    DIVIDE(_topRev, _totalRev, 0)
		formatString: 0.00%
		displayFolder: Product Analytics
		lineageTag: 1e5ef44c-688b-4bce-8816-2710f9d45c94

	/// Average revenue per staff member
	measure 'Revenue per Staff' =
			DIVIDE(
			    [Net Revenue],
			    DISTINCTCOUNT(fct_sales[staff_key]),
			    0
			)
		formatString: #,##0.00
		displayFolder: Staff Performance
		lineageTag: 0cf030b9-d0a3-40f6-8cc8-0b4cc0847604

	/// Average invoices per staff
	measure 'Invoices per Staff' =
			DIVIDE(
			    [Unique Invoices],
			    DISTINCTCOUNT(fct_sales[staff_key]),
			    0
			)
		formatString: #,##0.00
		displayFolder: Staff Performance
		lineageTag: 3d4864f1-d6c6-4177-b776-6c31e358a274

	/// Selected staff share vs all staff
	measure 'Staff Contribution %' =
			IF(
			    HASONEVALUE(dim_staff[staff_name]),
			    VAR _staffRev = [Net Revenue]
			    VAR _allRev = CALCULATE([Net Revenue], REMOVEFILTERS(dim_staff))
			    RETURN DIVIDE(_staffRev, _allRev, 0),
			    BLANK()
			)
		formatString: 0.00%
		displayFolder: Staff Performance
		lineageTag: 18fc5e6a-8a77-4879-b512-412c875f6c92

	/// Distinct staff in context
	measure 'Active Staff Count' = DISTINCTCOUNT(fct_sales[staff_key])
		formatString: #,##0
		displayFolder: Staff Performance
		lineageTag: e41d337a-99af-42ff-b284-dd3e43e9244c

	/// Average quantity per staff
	measure 'Avg Qty per Staff' =
			DIVIDE(
			    [Total Quantity],
			    DISTINCTCOUNT(fct_sales[staff_key]),
			    0
			)
		formatString: #,##0.00
		displayFolder: Staff Performance
		lineageTag: 1f640fbe-9cd1-4877-971d-8f04e48c18d4

	/// Net amount per unit
	measure 'Avg Unit Price' =
			CALCULATE(
			    DIVIDE(
			        SUM(fct_sales[net_amount]),
			        SUM(fct_sales[quantity]),
			        0
			    ),
			    fct_sales[is_return] = FALSE
			)
		formatString: #,##0.00
		displayFolder: Operational
		lineageTag: be1ce2ca-0f18-4272-89f3-09aed366d41c

	/// Basket size
	measure 'Avg Qty per Invoice' =
			DIVIDE(
			    [Total Quantity],
			    [Unique Invoices],
			    0
			)
		formatString: #,##0.00
		displayFolder: Operational
		lineageTag: f6072100-4ed5-47cb-be4f-cf59272440a5

	/// Revenue per calendar day (incl off days)
	measure 'Avg Daily Revenue (Calendar)' =
			DIVIDE(
			    [Net Revenue],
			    DISTINCTCOUNT(dim_date[full_date]),
			    0
			)
		formatString: #,##0.00
		displayFolder: Operational
		lineageTag: 8e5aeba1-1e1b-4f0b-b55f-e4cd2f7da7f6

	/// Revenue per day with sales activity
	measure 'Avg Daily Revenue (Active)' =
			VAR _activeDays = CALCULATE(
			    DISTINCTCOUNT(dim_date[full_date]),
			    fct_sales[sales_key] <> BLANK()
			)
			RETURN
			    DIVIDE([Net Revenue], _activeDays, 0)
		formatString: #,##0.00
		displayFolder: Operational
		lineageTag: 22835a7a-1225-41ae-9101-27e6ba0c44cc

	/// Invoices per active day
	measure 'Avg Daily Invoices' =
			VAR _activeDays = CALCULATE(
			    DISTINCTCOUNT(dim_date[full_date]),
			    fct_sales[sales_key] <> BLANK()
			)
			RETURN
			    DIVIDE([Unique Invoices], _activeDays, 0)
		formatString: #,##0.00
		displayFolder: Operational
		lineageTag: df4512b7-8576-43ab-be40-812ce91ddcc9

	/// Net Revenue month-to-date
	measure 'Revenue MTD' = CALCULATE([Net Revenue], DATESMTD(dim_date[full_date]))
		formatString: #,##0.00
		displayFolder: Time Intelligence
		lineageTag: c2606f24-4020-49d1-86d0-66316d12a3d1

	/// Net Revenue year-to-date
	measure 'Revenue YTD' = CALCULATE([Net Revenue], DATESYTD(dim_date[full_date]))
		formatString: #,##0.00
		displayFolder: Time Intelligence
		lineageTag: 65d6fe8d-052f-4eaa-8269-524277f6aa8a

	/// Net Revenue same period last year
	measure 'Revenue PY' = CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(dim_date[full_date]))
		formatString: #,##0.00
		displayFolder: Time Intelligence
		lineageTag: f15ef559-77d9-4535-94d3-2686b5bdb4bb

	/// Month-over-month revenue growth
	measure 'Revenue MoM %' =
			VAR _current = [Net Revenue]
			VAR _prev = CALCULATE([Net Revenue], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    DIVIDE(_current - _prev, ABS(_prev), BLANK())
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 1f03d478-b0ec-404e-8861-3271b6ad90af

	/// Year-over-year revenue growth
	measure 'Revenue YoY %' =
			VAR _current = [Net Revenue]
			VAR _prev = CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(dim_date[full_date]))
			RETURN
			    DIVIDE(_current - _prev, ABS(_prev), BLANK())
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 11ee9b32-78b5-4363-a800-5405cd3d879e

	/// Absolute MoM revenue change
	measure 'Revenue MoM Variance' =
			VAR _prev = CALCULATE([Net Revenue], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    IF(ISBLANK(_prev), BLANK(), [Net Revenue] - _prev)
		formatString: #,##0.00
		displayFolder: Time Intelligence
		lineageTag: 0970d601-0ad3-4d4e-9b00-6e3e510d1920

	/// Absolute YoY revenue change
	measure 'Revenue YoY Variance' = [Net Revenue] - CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(dim_date[full_date]))
		formatString: #,##0.00
		displayFolder: Time Intelligence
		lineageTag: 6841d15f-0e60-4cf3-a71f-c14fc814ff96

	/// Month-over-month quantity growth
	measure 'Quantity MoM %' =
			VAR _current = [Total Quantity]
			VAR _prev = CALCULATE([Total Quantity], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    DIVIDE(_current - _prev, ABS(_prev), BLANK())
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 979b17c6-4949-452b-9bef-287f6c7ee044

	/// Month-over-month invoice count growth
	measure 'Invoices MoM %' =
			VAR _current = [Unique Invoices]
			VAR _prev = CALCULATE([Unique Invoices], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    DIVIDE(_current - _prev, ABS(_prev), BLANK())
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: cb56f861-5dfd-43be-84ab-402c7dd079d2

	/// Month-over-month customer count growth
	measure 'Customers MoM %' =
			VAR _current = [Unique Customers]
			VAR _prev = CALCULATE([Unique Customers], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    DIVIDE(_current - _prev, ABS(_prev), BLANK())
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 993ef729-fdf5-48a6-98cf-249985ffa4c3

	/// 1=up, 0=flat, -1=down (MoM)
	measure 'Revenue MoM Direction' =
			VAR _c = [Net Revenue]
			VAR _p = CALCULATE([Net Revenue], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    IF(ISBLANK(_p), 0, IF(_c > _p, 1, IF(_c < _p, -1, 0)))
		formatString: 0
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: 695b023e-0707-4ca2-9ebf-503d899fb9ba

	/// 1=up, 0=flat, -1=down (YoY)
	measure 'Revenue YoY Direction' =
			VAR _c = [Net Revenue]
			VAR _p = CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(dim_date[full_date]))
			RETURN
			    IF(ISBLANK(_p), 0, IF(_c > _p, 1, IF(_c < _p, -1, 0)))
		formatString: 0
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: 0aea9999-d333-42af-a1da-190e64b83e46

	/// 1=up, 0=flat, -1=down (Qty MoM)
	measure 'Quantity MoM Direction' =
			VAR _c = [Total Quantity]
			VAR _p = CALCULATE([Total Quantity], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    IF(ISBLANK(_p), 0, IF(_c > _p, 1, IF(_c < _p, -1, 0)))
		formatString: 0
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: 070b7097-7822-43e9-b902-b0dd4a998ab8

	/// 1=up, 0=flat, -1=down (Invoices MoM)
	measure 'Invoices MoM Direction' =
			VAR _c = [Unique Invoices]
			VAR _p = CALCULATE([Unique Invoices], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    IF(ISBLANK(_p), 0, IF(_c > _p, 1, IF(_c < _p, -1, 0)))
		formatString: 0
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: d5c7aaf5-3353-469c-b5f0-c8b018928382

	/// 1=up, 0=flat, -1=down (Customers MoM)
	measure 'Customers MoM Direction' =
			VAR _c = [Unique Customers]
			VAR _p = CALCULATE([Unique Customers], PREVIOUSMONTH(dim_date[full_date]))
			RETURN
			    IF(ISBLANK(_p), 0, IF(_c > _p, 1, IF(_c < _p, -1, 0)))
		formatString: 0
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: 34220ef7-710b-4f31-b259-e6341c0fa063

	/// Hex color for Revenue MoM
	measure 'Revenue MoM Color' =
			VAR _pct = [Revenue MoM %]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_pct), "#9E9E9E",
			        _pct > 0.05, "#2E7D32",
			        _pct > 0, "#81C784",
			        _pct > -0.05, "#F57C00",
			        "#C62828"
			    )
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: abd4d6aa-2a59-4262-b7c2-3cb5313e1a63

	/// Hex color for Revenue YoY
	measure 'Revenue YoY Color' =
			VAR _pct = [Revenue YoY %]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_pct), "#9E9E9E",
			        _pct > 0.05, "#2E7D32",
			        _pct > 0, "#81C784",
			        _pct > -0.05, "#F57C00",
			        "#C62828"
			    )
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: 128a36e8-92b2-4ebe-8957-30fd07232b1c

	/// Inverted: high discount = red
	measure 'Discount Rate Color' =
			VAR _rate = [Discount Rate %]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_rate), "#9E9E9E",
			        _rate > 0.15, "#C62828",
			        _rate > 0.10, "#F57C00",
			        _rate > 0.05, "#81C784",
			        "#2E7D32"
			    )
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: 9a217345-a2ac-4a13-9637-f4d8a346aa4d

	/// Inverted: high returns = red
	measure 'Return Rate Color' =
			VAR _rate = [Return Rate %]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(_rate), "#9E9E9E",
			        _rate > 0.10, "#C62828",
			        _rate > 0.05, "#F57C00",
			        _rate > 0.02, "#81C784",
			        "#2E7D32"
			    )
		isHidden
		displayFolder: Conditional Formatting
		lineageTag: b064836b-bff5-4349-9296-c35214a2e7b3

	/// Text badge for MoM growth
	measure 'Revenue MoM Badge' =
			VAR _pct = [Revenue MoM %]
			RETURN
			    IF(
			        ISBLANK(_pct), "--",
			        IF(_pct >= 0,
			            "^ " & FORMAT(_pct, "0.0%"),
			            "v " & FORMAT(_pct, "0.0%")
			        )
			    )
		displayFolder: Conditional Formatting
		lineageTag: 37057bba-625e-41ba-b50d-4f9ca685dd5d

	/// Text badge for YoY growth
	measure 'Revenue YoY Badge' =
			VAR _pct = [Revenue YoY %]
			RETURN
			    IF(
			        ISBLANK(_pct), "--",
			        IF(_pct >= 0,
			            "^ " & FORMAT(_pct, "0.0%"),
			            "v " & FORMAT(_pct, "0.0%")
			        )
			    )
		displayFolder: Conditional Formatting
		lineageTag: 00385b5a-d793-4bae-a7c9-776ebefb9d7a

	/// Current vs 10% growth target over PY
	measure 'Revenue vs PY Target %' =
			VAR _current = [Net Revenue]
			VAR _py = CALCULATE([Net Revenue], SAMEPERIODLASTYEAR(dim_date[full_date]))
			VAR _target = _py * 1.1
			RETURN
			    DIVIDE(_current, _target, 0)
		formatString: 0.00%
		displayFolder: Conditional Formatting
		lineageTag: 4832dc46-291b-4c1a-a8b3-c3f6c95ae46d

	/// Product ranking by revenue
	measure 'Product Revenue Rank' =
			IF(
			    HASONEVALUE(dim_product[drug_name]),
			    RANKX(ALL(dim_product[drug_name]), [Net Revenue],, DESC, Dense),
			    BLANK()
			)
		formatString: #,##0
		displayFolder: Conditional Formatting
		lineageTag: fc70c4d3-71dd-43a8-9542-a8d60c77393c

	/// Staff ranking by revenue
	measure 'Staff Revenue Rank' =
			IF(
			    HASONEVALUE(dim_staff[staff_name]),
			    RANKX(ALL(dim_staff[staff_name]), [Net Revenue],, DESC, Dense),
			    BLANK()
			)
		formatString: #,##0
		displayFolder: Conditional Formatting
		lineageTag: 04e3e557-ba9a-434c-8e06-62334ebbc39a

	/// Rows with missing customer data
	measure 'Unknown Customer Rows' = CALCULATE(COUNTROWS(fct_sales), fct_sales[customer_key] = -1)
		formatString: #,##0
		displayFolder: Data Quality
		lineageTag: 3dea728c-d582-462d-b62e-e375b2b997d1

	/// Rows with missing staff data
	measure 'Unknown Staff Rows' = CALCULATE(COUNTROWS(fct_sales), fct_sales[staff_key] = -1)
		formatString: #,##0
		displayFolder: Data Quality
		lineageTag: e4e0316e-52ed-477a-b738-2e5e349e8572

	/// Rows with missing product data
	measure 'Unknown Product Rows' = CALCULATE(COUNTROWS(fct_sales), fct_sales[product_key] = -1)
		formatString: #,##0
		displayFolder: Data Quality
		lineageTag: 08f6a55d-b99f-4107-9fb7-a0ddb555dd13

	/// Anomaly: negative qty but not flagged as return
	measure 'Negative Qty Non-Return' =
			CALCULATE(
			    COUNTROWS(fct_sales),
			    fct_sales[quantity] < 0,
			    fct_sales[is_return] = FALSE
			)
		formatString: #,##0
		displayFolder: Data Quality
		lineageTag: 7aed855a-ad42-43b2-bfac-0b814e7c3f7f

	/// Rows with no matching date dimension
	measure 'Orphan Row Count' =
			COUNTROWS(
			    FILTER(fct_sales, ISBLANK(RELATED(dim_date[full_date])))
			)
		formatString: #,##0
		displayFolder: Data Quality
		lineageTag: 180f5614-2d44-46f9-9612-f16af459f519

	/// Dynamic period text for titles
	measure 'Selected Period Label' = "Period: " & FORMAT(MIN(dim_date[full_date]), "DD-MMM-YYYY") & " to " & FORMAT(MAX(dim_date[full_date]), "DD-MMM-YYYY")
		isHidden
		displayFolder: Report Helpers
		lineageTag: 03250623-b8ad-4fef-b6cd-4d45fa18e286

	/// Current year selection text
	measure 'Selected Year' =
			IF(
			    HASONEVALUE(dim_date[year]),
			    FORMAT(SELECTEDVALUE(dim_date[year]), "0"),
			    "Multiple Years"
			)
		isHidden
		displayFolder: Report Helpers
		lineageTag: fabd8f77-826b-4a67-b335-d930fe3f2683

	/// Active filter context for subtitles
	measure 'Filter State Text' =
			VAR _year = IF(HASONEVALUE(dim_date[year]), "Year: " & SELECTEDVALUE(dim_date[year]), "")
			VAR _billing = IF(HASONEVALUE(dim_billing[billing_group]), " | Billing: " & SELECTEDVALUE(dim_billing[billing_group]), "")
			VAR _product = IF(HASONEVALUE(dim_product[drug_category]), " | Category: " & SELECTEDVALUE(dim_product[drug_category]), "")
			RETURN
			    _year & _billing & _product
		isHidden
		displayFolder: Report Helpers
		lineageTag: c01faddc-89e1-483c-901b-9a2fce4a1778

	/// Data as of timestamp
	measure 'Last Refresh Date' = FORMAT(NOW(), "DD-MMM-YYYY HH:NN")
		isHidden
		displayFolder: Report Helpers
		lineageTag: c1c99e8d-5e08-4c6b-8d06-e0df7db57665

	/// For conditional visibility
	measure 'Has Data' = IF(COUNTROWS(fct_sales) > 0, TRUE, FALSE)
		isHidden
		displayFolder: Report Helpers
		lineageTag: 1c966dd4-d9ae-4ae0-823c-fc4cabe4d7e2

	/// Dynamic title for Overview page
	measure 'Title - Overview' = "Sales Overview | " & [Selected Period Label]
		isHidden
		displayFolder: Page Titles
		lineageTag: 721fd6ea-6e5e-4889-aeaa-57f6af992fb5

	/// Dynamic title for Revenue page
	measure 'Title - Revenue Analysis' = "Revenue Analysis" & IF(HASONEVALUE(dim_billing[billing_group]), " - " & SELECTEDVALUE(dim_billing[billing_group]), "") & " | " & [Selected Period Label]
		isHidden
		displayFolder: Page Titles
		lineageTag: 6460481b-81c7-4843-822e-a56db507c8a6

	/// Dynamic title for Product page
	measure 'Title - Product Performance' = "Product Performance" & IF(HASONEVALUE(dim_product[drug_category]), " - " & SELECTEDVALUE(dim_product[drug_category]), IF(HASONEVALUE(dim_product[drug_division]), " - " & SELECTEDVALUE(dim_product[drug_division]), "")) & " | " & [Selected Period Label]
		isHidden
		displayFolder: Page Titles
		lineageTag: a9e50171-71fc-4c3e-9a1f-2a10021bdae0

	/// Dynamic title for Customer page
	measure 'Title - Customer Insights' = "Customer Insights" & IF(HASONEVALUE(dim_customer[customer_name]), " - " & SELECTEDVALUE(dim_customer[customer_name]), "") & " | " & [Selected Period Label]
		isHidden
		displayFolder: Page Titles
		lineageTag: e1a4ff12-6bf5-4853-b6c7-f0d9765fd4b4

	/// Dynamic title for Staff page
	measure 'Title - Staff Performance' = "Staff Performance" & IF(HASONEVALUE(dim_staff[staff_name]), " - " & SELECTEDVALUE(dim_staff[staff_name]), IF(HASONEVALUE(dim_staff[staff_position]), " - " & SELECTEDVALUE(dim_staff[staff_position]), "")) & " | " & [Selected Period Label]
		isHidden
		displayFolder: Page Titles
		lineageTag: c3eadc38-651f-4be4-b5c9-580fb6b50204

	/// Dynamic title for Returns page
	measure 'Title - Returns Analysis' = "Returns Analysis" & IF(HASONEVALUE(dim_billing[billing_group]), " - " & SELECTEDVALUE(dim_billing[billing_group]), "") & " | " & [Selected Period Label]
		isHidden
		displayFolder: Page Titles
		lineageTag: 25e73c9c-5872-46a7-a25a-ae81e50c19fa

	/// Dynamic title for Discount page
	measure 'Title - Discount Analysis' = "Discount Analysis | " & [Selected Period Label]
		isHidden
		displayFolder: Page Titles
		lineageTag: a991dadb-b98d-4410-9be7-01670219fd70

	/// Dynamic title for Trends page
	measure 'Title - Trends' = "Trends & Time Intelligence" & IF(HASONEVALUE(dim_date[year]), " - " & FORMAT(SELECTEDVALUE(dim_date[year]), "0"), "") & IF(HASONEVALUE(dim_date[quarter_label]), " " & SELECTEDVALUE(dim_date[quarter_label]), "")
		isHidden
		displayFolder: Page Titles
		lineageTag: fc1a4c73-58b3-4848-ba09-ad1c0d3318c4

	/// Dynamic title for Data Quality page
	measure 'Title - Data Quality' = "Data Quality Dashboard | " & [Selected Period Label] & " | Refreshed: " & FORMAT(NOW(), "DD-MMM-YYYY HH:NN")
		isHidden
		displayFolder: Page Titles
		lineageTag: 4a34e249-59f5-4796-8896-e3c945e7d007

	/// Dynamic title for Validation page
	measure 'Title - Validation' = "Validation & Reconciliation | " & [Selected Period Label]
		isHidden
		displayFolder: Page Titles
		lineageTag: 3097cccc-a72b-4cc0-8f18-4865490cec7b

	/// Concatenated product summary for tooltip page
	measure 'Tooltip Product Summary' =
			VAR _name = SELECTEDVALUE(dim_product[drug_name], "Multiple Products")
			VAR _brand = SELECTEDVALUE(dim_product[drug_brand], "")
			VAR _cat = SELECTEDVALUE(dim_product[drug_category], "")
			VAR _status = SELECTEDVALUE(dim_product[drug_status], "")
			VAR _rev = FORMAT([Net Revenue], "#,##0")
			VAR _qty = FORMAT([Total Quantity], "#,##0")
			VAR _rank = FORMAT([Product Revenue Rank], "#,##0")
			RETURN
			    _name
			    & IF(_brand <> "", UNICHAR(10) & "Brand: " & _brand, "")
			    & IF(_cat <> "", UNICHAR(10) & "Category: " & _cat, "")
			    & IF(_status <> "", UNICHAR(10) & "Status: " & _status, "")
			    & UNICHAR(10) & "Revenue: " & _rev
			    & UNICHAR(10) & "Quantity: " & _qty
			    & IF(NOT ISBLANK([Product Revenue Rank]), UNICHAR(10) & "Rank: #" & _rank, "")
		displayFolder: Tooltips
		lineageTag: 89ead2df-1afd-47af-a7b4-62ea9c5eebfd

	/// Concatenated customer summary for tooltip page
	measure 'Tooltip Customer Summary' =
			VAR _name = SELECTEDVALUE(dim_customer[customer_name], "Multiple Customers")
			VAR _rev = FORMAT([Net Revenue], "#,##0")
			VAR _invCnt = FORMAT([Unique Invoices], "#,##0")
			VAR _avgInv = FORMAT([Avg Invoice Value], "#,##0.00")
			VAR _lastTx = FORMAT([Last Transaction Date], "DD-MMM-YYYY")
			RETURN
			    _name
			    & UNICHAR(10) & "Revenue: " & _rev
			    & UNICHAR(10) & "Invoices: " & _invCnt
			    & UNICHAR(10) & "Avg Invoice: " & _avgInv
			    & IF(NOT ISBLANK([Last Transaction Date]), UNICHAR(10) & "Last Txn: " & _lastTx, "")
		displayFolder: Tooltips
		lineageTag: 01839481-1324-4e78-ba8c-ed52abb05397

	/// Concatenated month summary for tooltip page
	measure 'Tooltip Month Summary' =
			VAR _period = SELECTEDVALUE(dim_date[year_month], "Multiple Periods")
			VAR _rev = FORMAT([Net Revenue], "#,##0")
			VAR _qty = FORMAT([Total Quantity], "#,##0")
			VAR _inv = FORMAT([Unique Invoices], "#,##0")
			VAR _cust = FORMAT([Unique Customers], "#,##0")
			VAR _mom = [Revenue MoM Badge]
			RETURN
			    _period
			    & UNICHAR(10) & "Revenue: " & _rev
			    & UNICHAR(10) & "Quantity: " & _qty
			    & UNICHAR(10) & "Invoices: " & _inv
			    & UNICHAR(10) & "Customers: " & _cust
			    & IF(_mom <> "--", UNICHAR(10) & "MoM: " & _mom, "")
		displayFolder: Tooltips
		lineageTag: 2136692a-68c3-419d-82fe-21dc189768fa

	/// Most recent transaction date in current filter context
	measure 'Last Transaction Date' = MAX(dim_date[full_date])
		formatString: DD-MMM-YYYY
		displayFolder: Tooltips
		lineageTag: 223e097b-bbf9-4a1a-9d4d-b7848fa9fa7c

	/// Unicode arrow badge for MoM revenue change
	measure 'Revenue MoM Arrow' =
			VAR _dir = [Revenue MoM Direction]
			VAR _pct = [Revenue MoM %]
			RETURN
			    IF(
			        ISBLANK(_pct), "--",
			        SWITCH(
			            _dir,
			            1, UNICHAR(9650) & " " & FORMAT(_pct, "0.0%"),
			            -1, UNICHAR(9660) & " " & FORMAT(_pct, "0.0%"),
			            UNICHAR(9654) & " " & FORMAT(_pct, "0.0%")
			        )
			    )
		displayFolder: Conditional Formatting
		lineageTag: 82e00e3c-79fe-443a-b8c4-9b9f59ad03fa

	/// Unicode arrow badge for YoY revenue change
	measure 'Revenue YoY Arrow' =
			VAR _dir = [Revenue YoY Direction]
			VAR _pct = [Revenue YoY %]
			RETURN
			    IF(
			        ISBLANK(_pct), "--",
			        SWITCH(
			            _dir,
			            1, UNICHAR(9650) & " " & FORMAT(_pct, "0.0%"),
			            -1, UNICHAR(9660) & " " & FORMAT(_pct, "0.0%"),
			            UNICHAR(9654) & " " & FORMAT(_pct, "0.0%")
			        )
			    )
		displayFolder: Conditional Formatting
		lineageTag: 5bdb0979-58b3-4998-af49-cec0f0f44207

	/// Unicode arrow badge for MoM invoice count change
	measure 'Invoices MoM Arrow' =
			VAR _dir = [Invoices MoM Direction]
			VAR _pct = [Invoices MoM %]
			RETURN
			    IF(
			        ISBLANK(_pct), "--",
			        SWITCH(
			            _dir,
			            1, UNICHAR(9650) & " " & FORMAT(_pct, "0.0%"),
			            -1, UNICHAR(9660) & " " & FORMAT(_pct, "0.0%"),
			            UNICHAR(9654) & " " & FORMAT(_pct, "0.0%")
			        )
			    )
		displayFolder: Conditional Formatting
		lineageTag: 23d12b11-5b6c-48df-9a17-dc89f85c04fb

	/// Unicode arrow badge for MoM customer count change
	measure 'Customers MoM Arrow' =
			VAR _dir = [Customers MoM Direction]
			VAR _pct = [Customers MoM %]
			RETURN
			    IF(
			        ISBLANK(_pct), "--",
			        SWITCH(
			            _dir,
			            1, UNICHAR(9650) & " " & FORMAT(_pct, "0.0%"),
			            -1, UNICHAR(9660) & " " & FORMAT(_pct, "0.0%"),
			            UNICHAR(9654) & " " & FORMAT(_pct, "0.0%")
			        )
			    )
		displayFolder: Conditional Formatting
		lineageTag: 05f0299c-93d6-4272-a446-e11b33daf189

	/// Unicode arrow badge for MoM quantity change
	measure 'Quantity MoM Arrow' =
			VAR _dir = [Quantity MoM Direction]
			VAR _pct = [Quantity MoM %]
			RETURN
			    IF(
			        ISBLANK(_pct), "--",
			        SWITCH(
			            _dir,
			            1, UNICHAR(9650) & " " & FORMAT(_pct, "0.0%"),
			            -1, UNICHAR(9660) & " " & FORMAT(_pct, "0.0%"),
			            UNICHAR(9654) & " " & FORMAT(_pct, "0.0%")
			        )
			    )
		displayFolder: Conditional Formatting
		lineageTag: d267b430-45da-4285-ad0a-7bdc36d46097

	/// Net Revenue resolved at governorate level for shape map
	measure 'Revenue by Governorate' =
			IF(
			    HASONEVALUE(dim_site[governorate]),
			    [Net Revenue],
			    BLANK()
			)
		formatString: #,##0
		displayFolder: Report Helpers
		lineageTag: 538b0bef-9967-4004-9155-a76c89a8dde8

	/// Returns 1 when Detail view is selected, 0 for Summary
	measure 'Is Detail View' =
			IF(
			    SELECTEDVALUE('_ViewToggle'[View], "Summary") = "Detail",
			    1,
			    0
			)
		formatString: 0
		isHidden
		displayFolder: Report Helpers
		lineageTag: ca7ebc14-6820-4d89-a9bf-b4763e9c7f2d

	/// Returns the selected display mode for KPI cards
	measure 'KPI Display Mode' = SELECTEDVALUE('_KPIDisplayMode'[Display Mode], "Absolute")
		isHidden
		displayFolder: Report Helpers
		lineageTag: cadbab19-0e74-4925-b475-0250651af593

	/// Switches between absolute Net Revenue and MoM % based on toggle
	measure 'KPI Dynamic Value' =
			IF(
			    [KPI Display Mode] = "Percentage",
			    [Revenue MoM %],
			    [Net Revenue]
			)
		formatStringExpression: =IF([KPI Display Mode] = "Percentage", "0.00%", "#,##0.00")
		displayFolder: Report Helpers
		lineageTag: 0dde5298-cea7-449a-9eed-85ac4d72afa6

	/// Percentage of customers with insurance transactions
	measure 'Insurance Customer %' =
			DIVIDE(
			    [Insurance Customers],
			    [Unique Customers],
			    0
			)
		formatString: 0.00%
		displayFolder: Customer Analytics
		lineageTag: f3c7e4d0-e118-4be9-b272-68f85bb258f8

	/// Percentage of distinct products sold that have Active status (count-based)
	measure 'Active Product Count %' =
			VAR _activeCount =
			    CALCULATE(
			        DISTINCTCOUNT(fct_sales[product_key]),
			        dim_product[drug_status] = "Active"
			    )
			VAR _totalCount = [Unique Products Sold]
			RETURN
			    DIVIDE(_activeCount, _totalCount, 0)
		formatString: 0.00%
		displayFolder: Product Analytics
		lineageTag: 77e6f0b8-ed27-40e1-8f74-940cfa641653

	column Value
		lineageTag: d898370a-2dcc-4987-bfd4-51fd3e15ef82
		isNameInferred
		sourceColumn: [Value]

	partition _Measures = calculated
		mode: import
		source = {BLANK()}

