"""Column name mapping: Excel header -> bronze.sales DB column."""

from __future__ import annotations

# Excel column name -> PostgreSQL column name
COLUMN_MAP: dict[str, str] = {
    "Reference No": "reference_no",
    "Date": "date",
    "Material": "material",
    "Material Desc.": "material_desc",
    "Quantity": "quantity",
    "Net Sales": "net_sales",
    "Gross Sales": "gross_sales",
    "Personel Number": "personel_number",
    "Person Name": "person_name",
    "Position": "position",
    "CATEGORY": "category",
    "DIVISION": "division",
    "Customer Name": "customer_name",
    "Brand": "brand",
    "Item Cluster": "item_cluster",
    "SUBCATEGORY": "subcategory",
    "SEGMENT": "segment",
    "Billing Type": "billing_type",
    "Certification": "certification",
    "Assignment": "assignment",
    "Salse Not TAX": "sales_not_tax",
    "Fi Document No.": "fi_document_no",
    "Insurance Tel": "insurance_tel",
    "Insurance No": "insurance_no",
    "Dis TAX": "dis_tax",
    "Paid": "paid",
    "KZWI1": "kzwi1",
    "CRM Order": "crm_order",
    "Ref.Return Date": "ref_return_date",
    "Ref.Return": "ref_return",
    "Buyer": "buyer",
    "Item Status": "item_status",
    "Subtotal5(Discount)": "subtotal5_discount",
    "Tax": "tax",
    "ADD_DIS": "add_dis",
    "Customer": "customer",
    "Mat.Group": "mat_group",
    "Mat. Group": "mat_group_short",
    "Item No": "item_no",
    "KNUMV": "knumv",
    "Billing Document": "billing_document",
    "Billing Type2": "billing_type2",
    "Cosm Mg": "cosm_mg",
    "Area Mg": "area_mg",
    "Site Name": "site_name",
    "Site": "site",
}
