"use client";

import { cn } from "@/lib/utils";

interface ThermalShiftReceiptProps {
  /** Legal company/pharmacy name shown at the top of the receipt. */
  companyName?: string;
  branchName: string;
  taxNo: string;
  terminalName: string;
  cashierName: string;
  openedAt: string;
  closedAt?: string | null;
  opening: number;
  cashSales: number;
  counted: number;
  shiftNumber?: string;
}

function fmt(n: number): string {
  return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function Line({ l, r }: { l: string; r: string }) {
  return (
    <div className="flex justify-between">
      <span>{l}</span>
      <span className="tabular-nums">{r}</span>
    </div>
  );
}

export function ThermalShiftReceipt({
  companyName = "Pharmacy",
  branchName,
  taxNo,
  terminalName,
  cashierName,
  openedAt,
  closedAt,
  opening,
  cashSales,
  counted,
  shiftNumber,
}: ThermalShiftReceiptProps) {
  const expected = opening + cashSales;
  const variance = counted - expected;
  const now = closedAt ?? new Date().toISOString();
  const docNo =
    shiftNumber ??
    `SH-${now.slice(2, 10).replaceAll("-", "")}-${terminalName.replace(/\D/g, "").slice(-2) || "01"}`;

  const opened = new Date(openedAt);
  const closed = new Date(now);

  return (
    <div
      className="relative mx-auto w-[320px] max-w-full rounded-[4px] px-[22px] py-5"
      style={{
        background: "#f4efe6",
        color: "#0a0a0a",
        fontFamily: "var(--font-jetbrains-mono), monospace",
        fontSize: 11.5,
        lineHeight: 1.5,
        fontVariantNumeric: "tabular-nums",
        boxShadow: "0 20px 50px rgba(0,0,0,0.5), inset 0 0 0 1px rgba(0,0,0,0.08)",
      }}
      data-testid="thermal-shift-receipt"
    >
      <PerforationStrip position="top" />

      <div className="text-center">
        <div
          className="font-[family-name:var(--font-fraunces)] font-semibold"
          style={{ fontSize: 17 }}
        >
          {companyName}
        </div>
        <div style={{ fontSize: 10 }}>{branchName}</div>
        <div style={{ fontSize: 10 }}>Tax No: {taxNo}</div>
      </div>

      <DottedRule />

      <div style={{ fontSize: 10 }} className="flex justify-between">
        <span>Shift {docNo}</span>
        <span>{closed.toISOString().slice(0, 16).replace("T", " ")}</span>
      </div>
      <div style={{ fontSize: 10 }} className="flex justify-between">
        <span>Cashier: {cashierName}</span>
        <span>{terminalName}</span>
      </div>
      <div style={{ fontSize: 10 }} className="flex justify-between">
        <span>Opened</span>
        <span>{opened.toISOString().slice(0, 16).replace("T", " ")}</span>
      </div>

      <DottedRule />

      <div style={{ fontSize: 10 }}>
        <Line l="Opening float" r={fmt(opening)} />
        <Line l="Cash sales" r={`+ ${fmt(cashSales)}`} />
        <DottedRule tight />
        <Line l="Expected" r={fmt(expected)} />
        <Line l="Counted" r={fmt(counted)} />
      </div>

      <DottedRule />

      <div
        className={cn(
          "flex justify-between font-bold",
          Math.abs(variance) < 1
            ? "text-[#137a3b]"
            : Math.abs(variance) < 20
              ? "text-[#8a5a00]"
              : "text-[#8a1a1a]",
        )}
        style={{ fontSize: 14 }}
        data-testid="receipt-variance"
      >
        <span>Variance</span>
        <span className="tabular-nums">
          {variance >= 0 ? "+" : "−"}
          {fmt(Math.abs(variance))} EGP
        </span>
      </div>

      <DottedRule />

      <div style={{ fontSize: 10 }} className="text-center">
        Report generated by DataPulse POS
        <br />
        datapulse.health / shifts / {docNo}
      </div>

      <div className="mt-2.5 flex justify-center gap-[1.5px]">
        {Array.from({ length: 42 }).map((_, i) => (
          <div
            key={i}
            className="bg-[#0a0a0a]"
            style={{ width: [1, 2, 1, 3, 1, 2][i % 6], height: 32 }}
          />
        ))}
      </div>
      <div
        className="mt-1 text-center"
        style={{ fontSize: 9, letterSpacing: "0.12em" }}
      >
        {docNo}
      </div>

      <PerforationStrip position="bottom" />
    </div>
  );
}

function DottedRule({ tight = false }: { tight?: boolean }) {
  return (
    <div
      style={{
        borderTop: "1px dashed #0a0a0a",
        margin: tight ? "4px 0" : "8px 0",
      }}
    />
  );
}

function PerforationStrip({ position }: { position: "top" | "bottom" }) {
  return (
    <div
      className="absolute left-0 right-0 h-3"
      style={{
        [position]: -6,
        background:
          "radial-gradient(circle at 8px 6px, transparent 4px, #f4efe6 4.5px)",
        backgroundSize: "16px 12px",
      }}
      aria-hidden="true"
    />
  );
}
